spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/teddie
spring.datasource.username=teddie
spring.datasource.password=teddie
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true